### Dashboard

@url = http://localhost:8080/dashboard

### Get Dashboard by dashboard Id

GET {{url}}/7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwcm9kLWRhc2hib2FyZCIsInN1YiI6InJhY2hlbEZyb21GcmllbmRzMjEiLCJhcHBfdXNlcl9pZCI6NywiYXV0aG9yaXRpZXMiOiJVU0VSIiwiZXhwIjoxNjgxOTI4NjU3fQ.66KzSksSMuc0B8uEVW_-rfjUjDLD4WZXZtYsTmIH_ac

### Get Dashboard by user Id

GET {{url}}/user/8 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwcm9kLWRhc2hib2FyZCIsInN1YiI6InJhY2hlbEZyb21GcmllbmRzMjgiLCJhcHBfdXNlcl9pZCI6OCwiYXV0aG9yaXRpZXMiOiJVU0VSIiwiZXhwIjoxNjgxOTI4ODM4fQ.4c2B_nq-6v8_mofqiZwZ8xf6sJNrIVsShW0BggRCr0o

### Create Dashboard

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwcm9kLWRhc2hib2FyZCIsInN1YiI6Im1pbGxlclRpbWUxMDAwIiwiYXBwX3VzZXJfaWQiOjIwLCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2ODI5NjQ3Njl9.Y5rImUrgj6HsBoX9noe_N3IOAkSTiAoKFfi7x1x9LNQ


{
    "dashboardName": "My Dashboard",
    "userId": 20
}

### Update Dashboard - dashboardId needs to match the url and the request body

PUT {{url}}/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwcm9kLWRhc2hib2FyZCIsInN1YiI6InJhY2hlbEZyb21GcmllbmRzNSIsImFwcF91c2VyX2lkIjoxLCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2ODE5MjE3MDV9.dnp7vvibsG1oShTGG5rmAu75x5sHyin5P5f0M1aQGjs

{   
    "dashboardId": 4,
    "dashboardName": "My Dashboard Updated",
    "userId": 1,
    "allWidgets": null
}


