### Dashboard

@url = http://localhost:8080/dashboard

GET {{url}}/1 HTTP/1.1

### Create Dashboard

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwcm9kLWRhc2hib2FyZCIsInN1YiI6InJhY2hlbEZyb21GcmllbmRzNSIsImFwcF91c2VyX2lkIjoxLCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2ODAxOTY4NDZ9.BjzRejSPpxzJRN1kaPvNvxW5zOLEkPgVtcT5Z5U9_XY


{
    "dashboardName": "My Dashboard",
    "userId": 1
}

### Update Dashboard

PUT {{url}}/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwcm9kLWRhc2hib2FyZCIsInN1YiI6InJhY2hlbEZyb21GcmllbmRzNSIsImFwcF91c2VyX2lkIjoxLCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2ODAxOTE4MDF9.qhL8hvbi-qAhG7D6JPYtoD2EyT-CA54RONYSF0pncvs

{   
    "dashboardId": 1,
    "dashboardName": "My Dashboard Updated",
    "userId": 1
}


