### Note

@url = http://localhost:8080/dashboard/noteWidget/note

### find all
GET {{url}} HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwcm9kLWRhc2hib2FyZCIsInN1YiI6Im1pbGxlclRpbWUxMDAwIiwiYXBwX3VzZXJfaWQiOjIsImF1dGhvcml0aWVzIjoiVVNFUiIsImV4cCI6MTY4MzMwNDE4NH0.UbAWLYdfoyKQ_q8Yv48Qs3qdEii-_vtex-llOgYqUJw

### find by date
GET {{url}}/byDate/2023-03-31 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwcm9kLWRhc2hib2FyZCIsInN1YiI6InJhY2hlbEZyb21GcmllbmRzNSIsImFwcF91c2VyX2lkIjoxLCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2ODAxOTc4Njh9.ak6dGqNovLRLzTnvtIWo9dXu_Em2kKlEs6cvdz7Gsk8

### find by note id
GET {{url}}/byId/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwcm9kLWRhc2hib2FyZCIsInN1YiI6InJhY2hlbEZyb21GcmllbmRzNSIsImFwcF91c2VyX2lkIjoxLCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2ODAxOTc4Njh9.ak6dGqNovLRLzTnvtIWo9dXu_Em2kKlEs6cvdz7Gsk8

### find by description
GET {{url}}/byDescription/Note desc
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwcm9kLWRhc2hib2FyZCIsInN1YiI6InJhY2hlbEZyb21GcmllbmRzNSIsImFwcF91c2VyX2lkIjoxLCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2ODAxOTcyNjF9.qU2qfPN5lRqGKrK6BvNviEIAYAGcUiRZhrrxVpdLO_s

### create note
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwcm9kLWRhc2hib2FyZCIsInN1YiI6InJhY2hlbEZyb21GcmllbmRzNSIsImFwcF91c2VyX2lkIjoxLCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2ODAxOTc4Njh9.ak6dGqNovLRLzTnvtIWo9dXu_Em2kKlEs6cvdz7Gsk8

{
    "title": "Note",
    "description": "Note description",
    "date": "2023-03-31",
    "noteWidget": 1
}

### update note 
PUT {{url}}/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwcm9kLWRhc2hib2FyZCIsInN1YiI6InJhY2hlbEZyb21GcmllbmRzNSIsImFwcF91c2VyX2lkIjoxLCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2ODAxOTY0MDB9.yGtAdV3cqhX5dGxpdLH1wJ7PaWTDFlQ4egKrq1O8s8I

{
    "noteId": 1,
    "title": "Note",
    "description": "Updated note description",
    "date": "2023-03-31",
    "noteWidget": 10
}


### delete note
DELETE {{url}}/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwcm9kLWRhc2hib2FyZCIsInN1YiI6InJhY2hlbEZyb21GcmllbmRzNSIsImFwcF91c2VyX2lkIjoxLCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2ODAxOTY0MDB9.yGtAdV3cqhX5dGxpdLH1wJ7PaWTDFlQ4egKrq1O8s8I