### Note

@url = http://localhost:8080/dashboard/note

### find all
GET {{url}} HTTP/1.1

### find by date
GET {{url}}/[date] HTTP/1.1
Authorization: Bearer [token]

### find by note id
@GET {{url}}/1
Authorization: Bearer [token]

### find by description
@GET {{url}}/[description]
Authorization: Bearer [token]

### create note
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer [token]

{
    "title": "Note",
    "description": "Note description",
    "date": "2023-03-03",
    "noteWidgetId": 1
}

### update note 
PUT {{url}}/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer [token]

{
    "title": "Note",
    "description": "Updated note description",
    "date": "2023-03-04",
    "noteWidgetId": 1
}


### delete note
DELETE {{url}}/1 HTTP/1.1
Authorization: Bearer [token]