### Note Widget

@url = http://localhost:8080/dashboard/noteWidget

### Create Note Widget

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwcm9kLWRhc2hib2FyZCIsInN1YiI6InJhY2hlbEZyb21GcmllbmRzNSIsImFwcF91c2VyX2lkIjoxLCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2ODAxOTY4NDZ9.BjzRejSPpxzJRN1kaPvNvxW5zOLEkPgVtcT5Z5U9_XY

{
    "title": "P1NK3Y3",
    "dashboardId": 1
}

###  Delete Note Widget

DELETE {{url}}/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwcm9kLWRhc2hib2FyZCIsInN1YiI6InJhY2hlbEZyb21GcmllbmRzNSIsImFwcF91c2VyX2lkIjoxLCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2ODAxOTIxMTB9.VXKtqmKa6HJj9DRHxJ6mRRv0tI82JHYW4otCk7q9L8Q
